[workspace]

resolver = "1"

members = [
    "mahjongg",
]

[profile.release]
opt-level     = "s"
codegen-units = 1
debug         = false
lto           = true
rpath         = false
strip         = true
