[package]
name    = "ui"
version = "0.1.0"
authors = ["Rodrigo Montegasppα Cacilhας <montegasppa@cacilhas.info>"]
license = "BSD-3-Clause"
edition = "2021"

[dependencies]

[dependencies.godot]
version = "0.1.3"
features = ["api-4-2"]

[lib]
crate-type = ["cdylib", "staticlib"]
